### ISSUE TITLE
Great Musicians from Babylon Pack DLC has 3 charges instead of 2.

### ISSUE THREAD

**Issue by mrobaczyk** [Infixo/Civ6-Real-Fixes#32]
Great Musicians from Babylon Pack DLC has 3 charges instead of 2.

Similar to https://github.com/Infixo/Civ6-Real-Fixes/issues/10.

**Comment by Infixo** [comment]
There are music samples attached to those, so I don't think that was a mistake. Maybe they wanted those new GMs be better. Anyway, would be shame to remove the neatly done music samples. I've corrected the tourism and culture yields, but I will keep the 3 GWs.

**Comment by mrobaczyk** [comment]
IMO it's the same as in #10 - "I forgot that we'd decided to nerf those", but I'm ok with your decision.
