### ISSUE TITLE
Oracle, Divine Spark, and Theater Squares

### ISSUE THREAD

**Issue by whorble** [Infixo/Civ6-Real-Fixes#35]
Theater squares give 3 different great person point types, but the Oracle only boosts one type.

For reference, there's also the Bologna/Stockholm city state bonus and the level 2 cultural alliance trade route bonus, that already give all 3 TS great person point types.

My fix:

```sql
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
	('ORACLE_GREATARTISTPOINTS',   'MODIFIER_SINGLE_CITY_DISTRICTS_ADJUST_GREAT_PERSON_POINTS', 'DISTRICT_IS_THEATER'),
	('ORACLE_GREATMUSICIANPOINTS', 'MODIFIER_SINGLE_CITY_DISTRICTS_ADJUST_GREAT_PERSON_POINTS', 'DISTRICT_IS_THEATER');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
	('ORACLE_GREATARTISTPOINTS',   'GreatPersonClassType', 'GREAT_PERSON_CLASS_ARTIST'),
	('ORACLE_GREATMUSICIANPOINTS', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_MUSICIAN'),
	('ORACLE_GREATARTISTPOINTS',   'Amount', 2),
	('ORACLE_GREATMUSICIANPOINTS', 'Amount', 2);
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
	('BUILDING_ORACLE', 'ORACLE_GREATARTISTPOINTS'),
	('BUILDING_ORACLE', 'ORACLE_GREATMUSICIANPOINTS');
```

The Divine Spark pantheon has the same issue, but may be more controversial. (For example, if we added artists and musicians to that, should we not also add great scientist points to universities and research labs? Should archaeological museums also count (since they don't for the Frescoes policy)? Are the answers the same for the vanilla district version vs the GS building version?)

Anyway, here's my take on Divine Spark, based on the Amphitheater data from Expansion2_Beliefs.xml:

```sql
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
	('DIVINE_SPARK_ARTIST',            'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',            'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('DIVINE_SPARK_MUSICIAN',          'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',            'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('DIVINE_SPARK_ARTIST_MODIFIER',   'MODIFIER_SINGLE_CITY_ADJUST_GREAT_PERSON_POINT', 'BUILDING_IS_MUSEUM_ART'),
	('DIVINE_SPARK_MUSICIAN_MODIFIER', 'MODIFIER_SINGLE_CITY_ADJUST_GREAT_PERSON_POINT', 'BUILDING_IS_BROADCAST_CENTER');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
	('DIVINE_SPARK_ARTIST',            'ModifierId',           'DIVINE_SPARK_ARTIST_MODIFIER'),
	('DIVINE_SPARK_MUSICIAN',          'ModifierId',           'DIVINE_SPARK_MUSICIAN_MODIFIER'),
	('DIVINE_SPARK_ARTIST_MODIFIER',   'GreatPersonClassType', 'GREAT_PERSON_CLASS_ARTIST'),
	('DIVINE_SPARK_MUSICIAN_MODIFIER', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_MUSICIAN'),
	('DIVINE_SPARK_ARTIST_MODIFIER',   'Amount',               1),
	('DIVINE_SPARK_MUSICIAN_MODIFIER', 'Amount',               1);
INSERT INTO BeliefModifiers (BeliefType, ModifierId) VALUES
	('BELIEF_DIVINE_SPARK', 'DIVINE_SPARK_ARTIST'),
	('BELIEF_DIVINE_SPARK', 'DIVINE_SPARK_MUSICIAN');
```

**Comment by Infixo** [comment]
Divine Spark's description is pretty clear and precisely says where it applies (_+1 Great Person point from Holy Site (Prophet), Campus (Scientist), and Theater Square (Writer) districts_). It works precisely like this. No problem here.

**Comment by Infixo** [comment]
Oracle. That one is tougher. However, I think lack of Artists and Musicians is what Firaxis intended. My reasons.
1. There is an explicit example in the description about Theater Square saying only about Writers.
2. This is a wonder from the ancient/classical times. Artists and Musicians are available from Renaissance and Industrial respectively. I think this is deliberate.
3. This is a base game wonder. They created 7 modifiers for it and it really was no problem to create 2 more. But they didn't. Not in 6+ years since it appeared.
On the other hand, Bologna's (and Stockholm) bonus can be acquired at any time during a game, so it makes sense for them to work on all Great People Classes.
